#!/bin/csh -f
################################################################################
# simulation top script
# change modelsim in this file dir and run "do this_file.do"
# project dir ---+---> hdl source dir
#                +---> sim script dir
#
################################################################################

# check if current dir has modelsim config file
set has_config  [file exists modelsim.do]
# config modelsim 
if {$has_config==1} { do modelsim.do  ; }

echo "+====================================="
echo "| Creat Lib Work soc                  "
echo "+====================================="
vlib work
vmap work work 

echo "+====================================="
echo "| Complile RTL Code of soc            "
echo "+====================================="
vlog -v ./dut/*.v ./tb/*.v

echo "+====================================="
echo "| Compiler Pass                       "
echo "| Being to Run Simulation             "
echo "+====================================="
vsim work.example_sim -t 1us

###################################### mus  ####################################

add wave -noupdate -format logic -radix hexadecimal example_sim/clock_
add wave -noupdate -format logic -radix hexadecimal example_sim/reset_


add wave -noupdate -format logic -radix float32 example_sim/cordicdut/io_in_x0
add wave -noupdate -format logic -radix hexadecimal example_sim/cordicdut/io_in_x0
add wave -noupdate -format logic -radix float32 example_sim/cordicdut/io_in_y0
add wave -noupdate -format logic -radix hexadecimal example_sim/cordicdut/io_in_y0
add wave -noupdate -format logic -radix float32 example_sim/cordicdut/io_in_z0
add wave -noupdate -format logic -radix hexadecimal example_sim/cordicdut/io_in_z0

add wave -noupdate -format logic -radix float32 example_sim/cordicdut/io_out_x
add wave -noupdate -format logic -radix hexadecimal example_sim/cordicdut/io_out_x
add wave -noupdate -format logic -radix float32 example_sim/cordicdut/io_out_y
add wave -noupdate -format logic -radix hexadecimal example_sim/cordicdut/io_out_y
add wave -noupdate -format logic -radix float32 example_sim/cordicdut/io_out_z

add wave -noupdate -format logic -radix hexadecimal example_sim/cordicdut/*
add wave -noupdate -format logic -radix float32 example_sim/clzdut/*
run 400us
